disabled_rules:
    - identifier_name
    - line_length
    - type_body_length
    - function_body_length
    - type_name
    - file_length
    - block_based_kvo
    - cyclomatic_complexity
    - nesting

